### ISSUE TITLE
Surface last-seen media

### ISSUE THREAD

**Issue by jhansche** [jhansche/ha-birdbuddy#4]
With v0.0.4, we added bird collections to the Media browser.

We also get thumbnail and photo info when a new postcard arrives (even if we haven't added it to a collection yet). Using this information we can download the latest postcard images as they arrive, and if we save it as a single filename, then its location can be predictable and could be surfaced with a local media URI.

As of v0.0.5, we do now have events and device triggers, so it is possible to do this now on your own, with an automation that calls `download_file`, using `data_template` to extract the URL from the event trigger (this is untested currently):
```
action:
  - service: downloader.download_file
    data:
      url: "{{ trigger.event.data.sighting.medias[0].contentUrl }}"
      subdir: "birdbuddy"
      filename: "last_postcard.jpg"
      overwrite: True
```

cc @Snille

**Comment by Snille** [comment]
Woho!! Thank you! :) I just got the "beta" option now! :)
Downloading and setting it up!

Happy new year!! :)

**Comment by Snille** [comment]
You are moving fast! Thank you. :)
I guess the above automation can be updated?
This is what I did (not tested yet)...

```
alias: Bird Buddy - Postcard
description: Bird Buddy is sending a postcard.
trigger:
  - platform: device
    device_id: <my id>
    domain: birdbuddy
    type: new_postcard
    feeder_id: <my id>
condition: []
action:
  - service: birdbuddy.collect_postcard
    data:
      strategy: best_guess
      best_guess_confidence: 10
      postcard: "{{ trigger.event.data.postcard }}"
      sighting: "{{ trigger.event.data.sighting }}"
  - service: downloader.download_file
    data:
      subdir: birdbuddy
      filename: last_postcard.jpg
      overwrite: true
mode: single
```

Not sure if the collect part is necessary?
Just wating for a bird to show... :)
Also, fyi, the "data_template" is only "data" now days in HA. :)
