### ISSUE TITLE
Accept videos in postcards 

### ISSUE THREAD

**Issue by jhansche** [jhansche/ha-birdbuddy#43]
Even though the schema allows videos in `.medias`, a new `.videoMedia` field was added which we are not currently requesting. So the postcard data we get back does not include videos, so they are not saved.

**Comment by jhansche** [comment]
jhansche/pybirdbuddy#6 adds the `videoMedia` field to be returned alongside `medias`, so an automation can be used to download the video files, if one is present. However, I don't know if that is enough to make the `collect_postcard` service save the video file along with other sighting media.

That change was released in [v0.0.11](https://github.com/jhansche/ha-birdbuddy/releases/tag/v0.0.11), so if anyone is able to test with their own postcards and report back if video media are now saved into collections, that would be helpful to know. If not, I'll have to wait until I get my next visitor with a video.

I will leave this open until that can be confirmed, because this issue is specifically about saving the video into the BB collections.

**Comment by CumpsD** [comment]
Updated in my HA and will wait for a bird to check the new event data, thanks

**Comment by jhansche** [comment]
Finally got a bird today. I can see that we receive the videoMedia field, but it doesn't have the video to collections. It could be used to download the video in the automation though.

I'll disable my auto collection and wait for the next visitor to see if I can debug the app and see what it does. It might just be a separate call to save the mediaId directly.

**Comment by CumpsD** [comment]
Got a bird today, I can confirm it is in the event now

```
videoMedia:
          id: xxx
          createdAt: '2023-02-06T14:36:30.347Z'
          thumbnailUrl: >-
            https://media.app-api-graphql.app-api.prod.aws.mybirdbuddy.com/media/feeder/xxx/media/xxx/THUMBNAIL.jpg?Expires=xxx
          contentUrl: >-
            https://media.app-api-graphql.app-api.prod.aws.mybirdbuddy.com/media/feeder/xxx/media/xxx/CONTENT.mp4?Expires=xxx
          __typename: MediaVideo
```

This is what I wanted, thanks :)
