### ISSUE TITLE
Auto Collect Postcards Automation 

### ISSUE THREAD

**Issue by sankeerthb** [jhansche/ha-birdbuddy#56]
The firmware update is working flawlessly. I"m can leave the feeder outside now even for updates. Thank you for great work.

I'm trying to setup automation to collect postcards automatically based on best guess. I have over 100 postcards from last week. The documentation isn't so clear. Below is the automation and error. I believe the sightings id has to be declared but not sure what exactly is needed. 
=============
alias: BirdBuddy Auto Collect
description: ""
trigger:
  - platform: device
    device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: birdbuddy
    type: new_postcard
    feeder_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
condition: []
action:
  - service: birdbuddy.collect_postcard
    data:
      strategy: best_guess
      best_guess_confidence: 10
      postcard: {}
      sighting: {}
mode: single
========================
Bird Buddy: Collect a Postcard
Stopped because an error was encountered at March 13, 2023 at 11:51:51 PM (runtime: 0.03 seconds)
must contain at least one of id. for dictionary value @ data['postcard']
========================
Similarly have one for Device Trigger too.

alias: BirdBuddy Device Trigger
description: ""
trigger:
  - platform: device
    device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: birdbuddy
    type: new_postcard
    feeder_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
condition: []
action:
  - service: birdbuddy.collect_postcard
    data:
      strategy: best_guess
      best_guess_confidence: 10
      postcard: trigger.event.data.postcard
      sighting: trigger.event.data.sighting
mode: single

**Comment by jhansche** [comment]
The service data should be passed through from the event trigger data:

```
action:
  - service: birdbuddy.collect_postcard
    data_template:
      strategy: best_guess
      best_guess_confidence: 10
      share_media: true
      postcard: "{{ trigger.event.data.postcard }}"
      sighting: "{{ trigger.event.data.sighting }}"
    enabled: true
```

Eventually I'll add this as a device action which will make it much easier to configure in the UI.
